// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJAHSJLxo4ovAZGaCTgHTV6zMH_NbImdo',
    appId: '1:807862629944:web:4adcb3c0b3ed3f63bd58cd',
    messagingSenderId: '807862629944',
    projectId: 'urban-culture-5c99b',
    authDomain: 'urban-culture-5c99b.firebaseapp.com',
    storageBucket: 'urban-culture-5c99b.appspot.com',
    measurementId: 'G-23NJ8X39HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpSwButIMdTZiFkuvQ476YGLmmhf7zKSE',
    appId: '1:807862629944:android:7d8bff7faddec80ebd58cd',
    messagingSenderId: '807862629944',
    projectId: 'urban-culture-5c99b',
    storageBucket: 'urban-culture-5c99b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAdaG9Ii-bohcd9udyNKRpoVype3dl7VU',
    appId: '1:807862629944:ios:49fd62fdd68df52dbd58cd',
    messagingSenderId: '807862629944',
    projectId: 'urban-culture-5c99b',
    storageBucket: 'urban-culture-5c99b.appspot.com',
    iosBundleId: 'com.example.urbanCulture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAdaG9Ii-bohcd9udyNKRpoVype3dl7VU',
    appId: '1:807862629944:ios:195544b2b87ca9f1bd58cd',
    messagingSenderId: '807862629944',
    projectId: 'urban-culture-5c99b',
    storageBucket: 'urban-culture-5c99b.appspot.com',
    iosBundleId: 'com.example.urbanCulture.RunnerTests',
  );
}
